-- AlterTable
ALTER TABLE "Board" ADD COLUMN "gridColor" TEXT NOT NULL DEFAULT '#ffffff';
ALTER TABLE "Board" ADD COLUMN "gridOpacity" DOUBLE PRECISION NOT NULL DEFAULT 0.08;
ALTER TABLE "Board" ADD COLUMN "gridLineWidth" DOUBLE PRECISION NOT NULL DEFAULT 1;
