/** PHB 2024 adventuring gear — canonical names and Spanish translations. */

export const GEAR_CATALOG = [
  { id: "acid", nameEn: "Acid", nameEs: "Ácido", cost: "25 gp" },
  { id: "alchemists-fire", nameEn: "Alchemist's Fire", nameEs: "Fuego alquímico", cost: "50 gp" },
  { id: "ammunition-arrows", nameEn: "Ammunition (Arrows)", nameEs: "Munición (flechas)", cost: "1 gp" },
  { id: "ammunition-bolts", nameEn: "Ammunition (Crossbow Bolts)", nameEs: "Munición (virotes)", cost: "1 gp" },
  { id: "ammunition-bullets", nameEn: "Ammunition (Firearm Bullets)", nameEs: "Munición (balas de fuego)", cost: "3 gp" },
  { id: "ammunition-needles", nameEn: "Ammunition (Blowgun Needles)", nameEs: "Munición (agujas de cerbatana)", cost: "1 gp" },
  { id: "antitoxin", nameEn: "Antitoxin", nameEs: "Antitoxina", cost: "50 gp" },
  { id: "arcane-focus-crystal", nameEn: "Arcane Focus (Crystal)", nameEs: "Foco arcano (cristal)", cost: "10 gp" },
  { id: "arcane-focus-orb", nameEn: "Arcane Focus (Orb)", nameEs: "Foco arcano (orbe)", cost: "20 gp" },
  { id: "arcane-focus-rod", nameEn: "Arcane Focus (Rod)", nameEs: "Foco arcano (varita)", cost: "10 gp" },
  { id: "arcane-focus-staff", nameEn: "Arcane Focus (Staff)", nameEs: "Foco arcano (bastón)", cost: "5 gp" },
  { id: "arcane-focus-wand", nameEn: "Arcane Focus (Wand)", nameEs: "Foco arcano (varita)", cost: "10 gp" },
  { id: "backpack", nameEn: "Backpack", nameEs: "Mochila", cost: "2 gp" },
  { id: "ball-bearings", nameEn: "Ball Bearings", nameEs: "Canicas de metal", cost: "1 gp" },
  { id: "barrel", nameEn: "Barrel", nameEs: "Barril", cost: "2 gp" },
  { id: "bedroll", nameEn: "Bedroll", nameEs: "Saco de dormir", cost: "1 gp" },
  { id: "bell", nameEn: "Bell", nameEs: "Campana", cost: "1 gp" },
  { id: "blanket", nameEn: "Blanket", nameEs: "Manta", cost: "5 sp" },
  { id: "block-and-tackle", nameEn: "Block and Tackle", nameEs: "Polispasto", cost: "1 gp" },
  { id: "book", nameEn: "Book", nameEs: "Libro", cost: "25 gp" },
  { id: "bottle-glass", nameEn: "Bottle, Glass", nameEs: "Botella de cristal", cost: "2 gp" },
  { id: "bucket", nameEn: "Bucket", nameEs: "Cubo", cost: "5 cp" },
  { id: "burglars-pack", nameEn: "Burglar's Pack", nameEs: "Equipo de ladrón", cost: "16 gp" },
  { id: "caltrops", nameEn: "Caltrops", nameEs: "Abrojos", cost: "1 gp" },
  { id: "candle", nameEn: "Candle", nameEs: "Vela", cost: "1 cp" },
  { id: "case-crossbow-bolt", nameEn: "Case, Crossbow Bolt", nameEs: "Funda para virotes", cost: "1 gp" },
  { id: "case-map-scroll", nameEn: "Case, Map or Scroll", nameEs: "Funda para mapa o pergamino", cost: "1 gp" },
  { id: "chain", nameEn: "Chain", nameEs: "Cadena", cost: "5 gp" },
  { id: "chest", nameEn: "Chest", nameEs: "Cofre", cost: "5 gp" },
  { id: "climbers-kit", nameEn: "Climber's Kit", nameEs: "Equipo de escalada", cost: "25 gp" },
  { id: "clothes-common", nameEn: "Clothes, Common", nameEs: "Ropa común", cost: "7 sp" },
  { id: "clothes-costume", nameEn: "Clothes, Costume", nameEs: "Ropa de disfraz", cost: "5 gp" },
  { id: "clothes-fine", nameEn: "Clothes, Fine", nameEs: "Ropa fina", cost: "15 gp" },
  { id: "clothes-travelers", nameEn: "Clothes, Traveler's", nameEs: "Ropa de viaje", cost: "2 gp" },
  { id: "component-pouch", nameEn: "Component Pouch", nameEs: "Bolsa de componentes", cost: "25 gp" },
  { id: "crowbar", nameEn: "Crowbar", nameEs: "Palanca", cost: "2 gp" },
  { id: "druidic-focus-sprig", nameEn: "Druidic Focus (Sprig of Mistletoe)", nameEs: "Foco druídico (muérdago)", cost: "1 gp" },
  { id: "druidic-focus-totem", nameEn: "Druidic Focus (Totem)", nameEs: "Foco druídico (tótem)", cost: "1 gp" },
  { id: "druidic-focus-wooden-staff", nameEn: "Druidic Focus (Wooden Staff)", nameEs: "Foco druídico (bastón de madera)", cost: "5 gp" },
  { id: "druidic-focus-yew-wand", nameEn: "Druidic Focus (Yew Wand)", nameEs: "Foco druídico (varita de tejo)", cost: "10 gp" },
  { id: "dungeoneers-pack", nameEn: "Dungeoneer's Pack", nameEs: "Equipo de explorador de mazmorras", cost: "12 gp" },
  { id: "entertainers-pack", nameEn: "Entertainer's Pack", nameEs: "Equipo de artista", cost: "40 gp" },
  { id: "explorers-pack", nameEn: "Explorer's Pack", nameEs: "Equipo de explorador", cost: "10 gp" },
  { id: "flask", nameEn: "Flask", nameEs: "Frasco", cost: "2 cp" },
  { id: "grappling-hook", nameEn: "Grappling Hook", nameEs: "Garfio", cost: "2 gp" },
  { id: "healers-kit", nameEn: "Healer's Kit", nameEs: "Botiquín", cost: "5 gp" },
  { id: "holy-symbol-amulet", nameEn: "Holy Symbol (Amulet)", nameEs: "Símbolo sagrado (amuleto)", cost: "5 gp" },
  { id: "holy-symbol-emblem", nameEn: "Holy Symbol (Emblem)", nameEs: "Símbolo sagrado (emblema)", cost: "5 gp" },
  { id: "holy-symbol-reliquary", nameEn: "Holy Symbol (Reliquary)", nameEs: "Símbolo sagrado (relicario)", cost: "5 gp" },
  { id: "holy-water", nameEn: "Holy Water", nameEs: "Agua bendita", cost: "25 gp" },
  { id: "hunting-trap", nameEn: "Hunting Trap", nameEs: "Trampa de caza", cost: "5 gp" },
  { id: "ink", nameEn: "Ink", nameEs: "Tinta", cost: "10 gp" },
  { id: "ink-pen", nameEn: "Ink Pen", nameEs: "Pluma", cost: "2 cp" },
  { id: "jug", nameEn: "Jug", nameEs: "Jarra", cost: "2 cp" },
  { id: "ladder", nameEn: "Ladder", nameEs: "Escalera", cost: "1 sp" },
  { id: "lamp", nameEn: "Lamp", nameEs: "Lámpara", cost: "5 sp" },
  { id: "lantern-bullseye", nameEn: "Lantern, Bullseye", nameEs: "Linterna de reflector", cost: "10 gp" },
  { id: "lantern-hooded", nameEn: "Lantern, Hooded", nameEs: "Linterna encapuchada", cost: "5 gp" },
  { id: "lock", nameEn: "Lock", nameEs: "Cerradura", cost: "10 gp" },
  { id: "magnifying-glass", nameEn: "Magnifying Glass", nameEs: "Lupa", cost: "100 gp" },
  { id: "manacles", nameEn: "Manacles", nameEs: "Grilletes", cost: "2 gp" },
  { id: "map", nameEn: "Map", nameEs: "Mapa", cost: "1 gp" },
  { id: "mirror", nameEn: "Mirror", nameEs: "Espejo", cost: "5 gp" },
  { id: "net", nameEn: "Net", nameEs: "Red", cost: "1 gp" },
  { id: "oil", nameEn: "Oil", nameEs: "Aceite", cost: "1 sp" },
  { id: "paper", nameEn: "Paper", nameEs: "Papel", cost: "2 sp" },
  { id: "parchment", nameEn: "Parchment", nameEs: "Pergamino", cost: "1 sp" },
  { id: "perfume", nameEn: "Perfume", nameEs: "Perfume", cost: "5 gp" },
  { id: "poison-basic", nameEn: "Poison, Basic", nameEs: "Veneno básico", cost: "100 gp" },
  { id: "pole", nameEn: "Pole", nameEs: "Palo", cost: "5 cp" },
  { id: "pot-iron", nameEn: "Pot, Iron", nameEs: "Olla de hierro", cost: "2 gp" },
  { id: "potion-of-healing", nameEn: "Potion of Healing", nameEs: "Poción de curación", cost: "50 gp" },
  { id: "pouch", nameEn: "Pouch", nameEs: "Bolsa", cost: "5 sp" },
  { id: "priests-pack", nameEn: "Priest's Pack", nameEs: "Equipo de sacerdote", cost: "33 gp" },
  { id: "quiver", nameEn: "Quiver", nameEs: "Carcaj", cost: "1 gp" },
  { id: "ram-portable", nameEn: "Ram, Portable", nameEs: "Ariete portátil", cost: "4 gp" },
  { id: "rations", nameEn: "Rations", nameEs: "Raciones", cost: "5 sp" },
  { id: "robes", nameEn: "Robes", nameEs: "Togas", cost: "1 gp" },
  { id: "rope", nameEn: "Rope", nameEs: "Cuerda", cost: "1 gp" },
  { id: "sack", nameEn: "Sack", nameEs: "Saco", cost: "1 cp" },
  { id: "scholars-pack", nameEn: "Scholar's Pack", nameEs: "Equipo de erudito", cost: "40 gp" },
  { id: "shovel", nameEn: "Shovel", nameEs: "Pala", cost: "2 gp" },
  { id: "signal-whistle", nameEn: "Signal Whistle", nameEs: "Silbato", cost: "5 cp" },
  { id: "spikes-iron", nameEn: "Spikes, Iron", nameEs: "Piquetas de hierro", cost: "1 gp" },
  { id: "spyglass", nameEn: "Spyglass", nameEs: "Catalejo", cost: "1,000 gp" },
  { id: "string", nameEn: "String", nameEs: "Cuerda fina", cost: "1 sp" },
  { id: "tent", nameEn: "Tent", nameEs: "Tienda de campaña", cost: "2 gp" },
  { id: "tinderbox", nameEn: "Tinderbox", nameEs: "Yesquero", cost: "5 sp" },
  { id: "torch", nameEn: "Torch", nameEs: "Antorcha", cost: "1 cp" },
  { id: "vial", nameEn: "Vial", nameEs: "Vial", cost: "1 gp" },
  { id: "waterskin", nameEn: "Waterskin", nameEs: "Odre", cost: "2 sp" },
];

export function gearCostEs(costEn) {
  return costEn
    .replace(/\b(\d+(?:,\d+)?)\s*gp\b/gi, "$1 po")
    .replace(/\b(\d+)\s*sp\b/gi, "$1 pp")
    .replace(/\b(\d+)\s*cp\b/gi, "$1 pc");
}
